import Head from "next/head";
import { useState } from "react";
import About from "../components/About";
import BackTopBtn from "../components/BackTopBtn";
import Contact from "../components/Contact";
import Header from "../components/Header";
import Hero from "../components/Hero";
import Products from "../components/Products";
import { products } from "../data/Products";

export default function Home({ products }) {
  const [animated, setAnimated] = useState("");

  return (
    <div>
      <Head>
        <title>Ecommerce Next</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css"
        />
      </Head>
      <Header setAnimated={setAnimated} />
      <Hero animated={animated} />
      <About animated={animated} />
      <Products products={products} />
      <Contact />
      <BackTopBtn />
    </div>
  );
}

export const getStaticProps = () => {
  return {
    props: {
      products: products,
    },
  };
};
